baseURL: "https://thedull.site"
title: thedull.site
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
# publishDir: "docs"
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

menu:
    main:
        # - name: Archive
        #   url: archives
        #   weight: 5
        # - name: Tags
        #   url: tags/
        #   weight: 10
        - name: Projects
          url: projects/
          weight: 10
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Igor@thedull.site"
    author: Igor Lushchyk

    defaultTheme: auto
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowToc: true
    # comments: false
    # images: ["papermod-cover.png"]

    homeInfoParams:
        # Title: "PaperMod"
        imageUrl: "avatar.png"
        imageTitle: me
        imageWidth: 150em
        Content: >
            Hello! My name is Igor!

            - Here I'll be writing about programming and my professional life.

            - I'm an **engineer** with focus on BigData and MLOps.

            - I'm and **mountaineer** - not so cool as Mesner but to cool to have photos which rocks \oo/.

            - Also I do **startups**. Tbh, most of them did fail.


    socialIcons:
        - name: github
          url: "#"
        - name: stackoverflow
          url: "#"
        - name: twitter
          url: "#"
        - name: RsS
          url: "index.xml"
        - name: email
          url: "#"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "favicon.ico"
        # favicon16x16: "<link / abs url>"
        # favicon32x32: "<link / abs url>"
        # apple_touch_icon: "<link / abs url>"
        # safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
     goldmark:
        renderer:
            unsafe: true
    # highlight:
    #     anchorLineNos: true
    #     codeFences: true
    #     guessSyntax: false
    #     lineNos: true
    #     # noClasses: false
    #     style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
